from typing import List, Any, Union
import logging
from a043_tes import a043_tes

class a043_tesDAO:
    def __init__(self, conexao):
        self.conexao = conexao
        self.tabela = "a043_tes"
        self.chave_primaria = "a043_codigo"
        self.logger = logging.getLogger(__name__)

    def _row_to_object(self, row: tuple) -> 'a043_tes':
        return a043_tes(
            a043_codigo=row[0],
            a043_sequencial=row[1],
            a043_descricao=row[2],
            a043_codigo_fiscal=row[3],
            a043_tipo_tes=row[4],
            a043_atualiza_est=row[5],
            a043_gera_financeiro=row[6],
            a043_estado=row[7],
            a043_obs=row[8],
            a043_mov_cta_capital=row[9],
            a043_mov_cta_socio=row[10],
            a043_mov_desp_secagem=row[11],
            a043_especie_pessoa=row[12],
            a043_cat_pessoa=row[13],
            a043_tributacao=row[14],
            a043_base_calc_icm=row[15],
            a043_icm=row[16],
            a043_cod_sit_trib=row[17],
            a043_mensagem_nf=row[18],
            a043_utiliza_preco_pauta=row[19],
            a043_funrural=row[20],
            a043_pis=row[21],
            a043_cofins=row[22],
            a043_ipi=row[23],
            a043_desc_cfop=row[24],
            a043_cod_pessoa=row[25],
            a043_operacao_tes=row[26],
            a043_mov_custo=row[27],
            a043_cod_tes_estorno=row[28],
            a043_cod_col_mapa=row[29],
            a043_finalidade_nfe=row[30],
            a043_mod_base_calculo=row[31],
            a043_mod_base_calculo_substituicao=row[32],
            a043_situacao_tributaria_cofins=row[33],
            a043_situacao_tributaria_pis=row[34],
            a043_base_calculo_cofins=row[35],
            a043_base_calculo_frete=row[36],
            a043_aliquota_frete=row[37],
            a043_obs_fiscal=row[38],
            a043_obs_contribuinte=row[39],
            a043_base_calculo_pis=row[40],
            a043_margem_subst_tributaria=row[41],
            a043_perc_red_base_cal_substituicao=row[42],
            a043_preco_produto=row[43],
            a043_permite_nf=row[44],
            a043_issqn=row[45],
            a043_bc_ipi=row[46],
            a043_mot_desoneracao=row[47],
            a043_exige_nf_prod=row[48],
            a043_vinculo_doc_fiscal=row[49],
            a043_funrural_ent_sai=row[50],
            a043_escrita=row[51],
            a043_ajuste_credito=row[52],
            a043_mensagem_nf_01=row[53],
            a043_tab_pis=row[54],
            a043_per_pis_socio=row[55],
            a043_base_pis_socio=row[56],
            a043_tab_cofins=row[57],
            a043_per_cofins_socio=row[58],
            a043_base_cofins_socio=row[59],
            a043_cod_Enq_ipi=row[60],
            a043_cst_ipi=row[61],
            a043_usa_trib_pis=row[62],
            a043_p_senar=row[63],
            a043_bc_senar=row[64],
            a043_usa_produtos=row[65],
            a043_cod_aj_apuracao_deducao=row[66],
            a043_cod_ocorrencia_aj_icms=row[67],
            a043_cod_reflexo_apur_icms=row[68],
            a043_cod_tipo_apuracao=row[69],
            a043_cod_responsabilidade=row[70],
            a043_cod_influencia_recolhimento=row[71],
            a043_cod_origem_tributacao=row[72],
            a043_cod_aj_icms_ex_icms=row[73],
            a043_cod_obrigacao_a_recolher=row[74],
            a043_cod_tipo_utilizacao_credito=row[75],
            a043_ajuste_debito=row[76],
            a043_cod_tipo_credito=row[77],
            a043_usa_senar=row[78],
            a043_usuario=row[79],
            a043_datetime=row[80],
            a043_pCredSN=row[81],
            a043_gera_sped=row[82],
            a043_permite_ibpt=row[83],
            a043_depreciacao_anual=row[84],
            a043_percentual_residual=row[85],
            a043_usa_funrural=row[86],
            a043_pDif=row[87],
            a043_pMVAST=row[88],
            a043_pEntMVAST=row[89],
            a043_AliqIntST=row[90],
            a043_AliqST=row[91],
            a043_envia_deposito=row[92],
            a043_tipo_preco=row[93],
            a043_pBCFCP=row[94],
            a043_pFCP=row[95],
            a043_pBCFCPST=row[96],
            a043_pFCPST=row[97],
            a043_pBCFCPRet=row[98],
            a043_pFCPRet=row[99],
            a043_pST=row[100],
            a043_usa_FCP=row[101],
            a043_usa_trib_serv=row[102],
            a043_red_bc_csll=row[103],
            a043_perc_csll=row[104],
            a043_red_bc_irrf=row[105],
            a043_perc_irrf=row[106],
            a043_red_bc_inss=row[107],
            a043_perc_inss=row[108],
            a043_bc_ret=row[109],
            a043_aliq_ret=row[110],
            a043_bc_ret_sub=row[111],
            a043_aliq_ret_sub=row[112],
            a043_perc_nret_princ=row[113],
            a043_perc_ret_15=row[114],
            a043_perc_ret_20=row[115],
            a043_perc_ret_25=row[116],
            a043_perc_nret_adic=row[117],
            a043_v_bc_st_ret_opc=row[118],
            a043_p_st_opc=row[119],
            a043_v_icms_substituto_opc=row[120],
            a043_v_icms_st_ret_opc=row[121],
            a043_v_bc_fcp_st_ret_opc=row[122],
            a043_p_fcp_st_ret_opc=row[123],
            a043_v_fcp_st_ret_opc=row[124],
            a043_p_red_bc_efet_opc=row[125],
            a043_v_bc_efet_opc=row[126],
            a043_p_icms_efet_opc=row[127],
            a043_v_icms_efet_opc=row[128],
            a043_v_bc_st_dest_opc=row[129],
            a043_v_icms_st_dest_opc=row[130],
            a043_v_bc_uf_dest=row[131],
            a043_v_bc_fcp_uf_dest_opc=row[132],
            a043_p_fcp_uf_dest_opc=row[133],
            a043_p_icms_uf_dest=row[134],
            a043_p_icms_inter=row[135],
            a043_p_icms_inter_part=row[136],
            a043_v_fcp_uf_dest_opc=row[137],
            a043_v_icms_uf_dest=row[138],
            a043_v_icms_uf_remet=row[139],
            a043_usa_cfop=row[140],
            a043_ibs=row[141],
            a043_ibs_aliquota=row[142],
            a043_ibs_base_calc=row[143],
            a043_iss=row[144],
            a043_iss_aliquota=row[145],
            a043_iss_base_calc=row[146],
            a043_cbs=row[147],
            a043_cbs_aliquota=row[148],
            a043_cbs_base_calc=row[149],
            a043_cod_iva=row[150],
            a043_cod_cidade=row[151],
            a043_cst_ibs=row[152],
            a043_cst_iss=row[153],
            a043_cst_cbs=row[154],
        )

    def insert(self, modelo: 'a043_tes') -> 'a043_tes':
        try:
            cursor = self.conexao.cursor()
            sql = f"""INSERT INTO {self.tabela} (a043_codigo, a043_sequencial, a043_descricao, a043_codigo_fiscal, a043_tipo_tes, a043_atualiza_est, a043_gera_financeiro, a043_estado, a043_obs, a043_mov_cta_capital, a043_mov_cta_socio, a043_mov_desp_secagem, a043_especie_pessoa, a043_cat_pessoa, a043_tributacao, a043_base_calc_icm, a043_icm, a043_cod_sit_trib, a043_mensagem_nf, a043_utiliza_preco_pauta, a043_funrural, a043_pis, a043_cofins, a043_ipi, a043_desc_cfop, a043_cod_pessoa, a043_operacao_tes, a043_mov_custo, a043_cod_tes_estorno, a043_cod_col_mapa, a043_finalidade_nfe, a043_mod_base_calculo, a043_mod_base_calculo_substituicao, a043_situacao_tributaria_cofins, a043_situacao_tributaria_pis, a043_base_calculo_cofins, a043_base_calculo_frete, a043_aliquota_frete, a043_obs_fiscal, a043_obs_contribuinte, a043_base_calculo_pis, a043_margem_subst_tributaria, a043_perc_red_base_cal_substituicao, a043_preco_produto, a043_permite_nf, a043_issqn, a043_bc_ipi, a043_mot_desoneracao, a043_exige_nf_prod, a043_vinculo_doc_fiscal, a043_funrural_ent_sai, a043_escrita, a043_ajuste_credito, a043_mensagem_nf_01, a043_tab_pis, a043_per_pis_socio, a043_base_pis_socio, a043_tab_cofins, a043_per_cofins_socio, a043_base_cofins_socio, a043_cod_Enq_ipi, a043_cst_ipi, a043_usa_trib_pis, a043_p_senar, a043_bc_senar, a043_usa_produtos, a043_cod_aj_apuracao_deducao, a043_cod_ocorrencia_aj_icms, a043_cod_reflexo_apur_icms, a043_cod_tipo_apuracao, a043_cod_responsabilidade, a043_cod_influencia_recolhimento, a043_cod_origem_tributacao, a043_cod_aj_icms_ex_icms, a043_cod_obrigacao_a_recolher, a043_cod_tipo_utilizacao_credito, a043_ajuste_debito, a043_cod_tipo_credito, a043_usa_senar, a043_usuario, a043_datetime, a043_pCredSN, a043_gera_sped, a043_permite_ibpt, a043_depreciacao_anual, a043_percentual_residual, a043_usa_funrural, a043_pDif, a043_pMVAST, a043_pEntMVAST, a043_AliqIntST, a043_AliqST, a043_envia_deposito, a043_tipo_preco, a043_pBCFCP, a043_pFCP, a043_pBCFCPST, a043_pFCPST, a043_pBCFCPRet, a043_pFCPRet, a043_pST, a043_usa_FCP, a043_usa_trib_serv, a043_red_bc_csll, a043_perc_csll, a043_red_bc_irrf, a043_perc_irrf, a043_red_bc_inss, a043_perc_inss, a043_bc_ret, a043_aliq_ret, a043_bc_ret_sub, a043_aliq_ret_sub, a043_perc_nret_princ, a043_perc_ret_15, a043_perc_ret_20, a043_perc_ret_25, a043_perc_nret_adic, a043_v_bc_st_ret_opc, a043_p_st_opc, a043_v_icms_substituto_opc, a043_v_icms_st_ret_opc, a043_v_bc_fcp_st_ret_opc, a043_p_fcp_st_ret_opc, a043_v_fcp_st_ret_opc, a043_p_red_bc_efet_opc, a043_v_bc_efet_opc, a043_p_icms_efet_opc, a043_v_icms_efet_opc, a043_v_bc_st_dest_opc, a043_v_icms_st_dest_opc, a043_v_bc_uf_dest, a043_v_bc_fcp_uf_dest_opc, a043_p_fcp_uf_dest_opc, a043_p_icms_uf_dest, a043_p_icms_inter, a043_p_icms_inter_part, a043_v_fcp_uf_dest_opc, a043_v_icms_uf_dest, a043_v_icms_uf_remet, a043_usa_cfop, a043_ibs, a043_ibs_aliquota, a043_ibs_base_calc, a043_iss, a043_iss_aliquota, a043_iss_base_calc, a043_cbs, a043_cbs_aliquota, a043_cbs_base_calc, a043_cod_iva, a043_cod_cidade, a043_cst_ibs, a043_cst_iss, a043_cst_cbs)
                      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"""
            params = (modelo.a043_codigo,
                modelo.a043_sequencial,
                modelo.a043_descricao,
                modelo.a043_codigo_fiscal,
                modelo.a043_tipo_tes,
                modelo.a043_atualiza_est,
                modelo.a043_gera_financeiro,
                modelo.a043_estado,
                modelo.a043_obs,
                modelo.a043_mov_cta_capital,
                modelo.a043_mov_cta_socio,
                modelo.a043_mov_desp_secagem,
                modelo.a043_especie_pessoa,
                modelo.a043_cat_pessoa,
                modelo.a043_tributacao,
                modelo.a043_base_calc_icm,
                modelo.a043_icm,
                modelo.a043_cod_sit_trib,
                modelo.a043_mensagem_nf,
                modelo.a043_utiliza_preco_pauta,
                modelo.a043_funrural,
                modelo.a043_pis,
                modelo.a043_cofins,
                modelo.a043_ipi,
                modelo.a043_desc_cfop,
                modelo.a043_cod_pessoa,
                modelo.a043_operacao_tes,
                modelo.a043_mov_custo,
                modelo.a043_cod_tes_estorno,
                modelo.a043_cod_col_mapa,
                modelo.a043_finalidade_nfe,
                modelo.a043_mod_base_calculo,
                modelo.a043_mod_base_calculo_substituicao,
                modelo.a043_situacao_tributaria_cofins,
                modelo.a043_situacao_tributaria_pis,
                modelo.a043_base_calculo_cofins,
                modelo.a043_base_calculo_frete,
                modelo.a043_aliquota_frete,
                modelo.a043_obs_fiscal,
                modelo.a043_obs_contribuinte,
                modelo.a043_base_calculo_pis,
                modelo.a043_margem_subst_tributaria,
                modelo.a043_perc_red_base_cal_substituicao,
                modelo.a043_preco_produto,
                modelo.a043_permite_nf,
                modelo.a043_issqn,
                modelo.a043_bc_ipi,
                modelo.a043_mot_desoneracao,
                modelo.a043_exige_nf_prod,
                modelo.a043_vinculo_doc_fiscal,
                modelo.a043_funrural_ent_sai,
                modelo.a043_escrita,
                modelo.a043_ajuste_credito,
                modelo.a043_mensagem_nf_01,
                modelo.a043_tab_pis,
                modelo.a043_per_pis_socio,
                modelo.a043_base_pis_socio,
                modelo.a043_tab_cofins,
                modelo.a043_per_cofins_socio,
                modelo.a043_base_cofins_socio,
                modelo.a043_cod_Enq_ipi,
                modelo.a043_cst_ipi,
                modelo.a043_usa_trib_pis,
                modelo.a043_p_senar,
                modelo.a043_bc_senar,
                modelo.a043_usa_produtos,
                modelo.a043_cod_aj_apuracao_deducao,
                modelo.a043_cod_ocorrencia_aj_icms,
                modelo.a043_cod_reflexo_apur_icms,
                modelo.a043_cod_tipo_apuracao,
                modelo.a043_cod_responsabilidade,
                modelo.a043_cod_influencia_recolhimento,
                modelo.a043_cod_origem_tributacao,
                modelo.a043_cod_aj_icms_ex_icms,
                modelo.a043_cod_obrigacao_a_recolher,
                modelo.a043_cod_tipo_utilizacao_credito,
                modelo.a043_ajuste_debito,
                modelo.a043_cod_tipo_credito,
                modelo.a043_usa_senar,
                modelo.a043_usuario,
                modelo.a043_datetime,
                modelo.a043_pCredSN,
                modelo.a043_gera_sped,
                modelo.a043_permite_ibpt,
                modelo.a043_depreciacao_anual,
                modelo.a043_percentual_residual,
                modelo.a043_usa_funrural,
                modelo.a043_pDif,
                modelo.a043_pMVAST,
                modelo.a043_pEntMVAST,
                modelo.a043_AliqIntST,
                modelo.a043_AliqST,
                modelo.a043_envia_deposito,
                modelo.a043_tipo_preco,
                modelo.a043_pBCFCP,
                modelo.a043_pFCP,
                modelo.a043_pBCFCPST,
                modelo.a043_pFCPST,
                modelo.a043_pBCFCPRet,
                modelo.a043_pFCPRet,
                modelo.a043_pST,
                modelo.a043_usa_FCP,
                modelo.a043_usa_trib_serv,
                modelo.a043_red_bc_csll,
                modelo.a043_perc_csll,
                modelo.a043_red_bc_irrf,
                modelo.a043_perc_irrf,
                modelo.a043_red_bc_inss,
                modelo.a043_perc_inss,
                modelo.a043_bc_ret,
                modelo.a043_aliq_ret,
                modelo.a043_bc_ret_sub,
                modelo.a043_aliq_ret_sub,
                modelo.a043_perc_nret_princ,
                modelo.a043_perc_ret_15,
                modelo.a043_perc_ret_20,
                modelo.a043_perc_ret_25,
                modelo.a043_perc_nret_adic,
                modelo.a043_v_bc_st_ret_opc,
                modelo.a043_p_st_opc,
                modelo.a043_v_icms_substituto_opc,
                modelo.a043_v_icms_st_ret_opc,
                modelo.a043_v_bc_fcp_st_ret_opc,
                modelo.a043_p_fcp_st_ret_opc,
                modelo.a043_v_fcp_st_ret_opc,
                modelo.a043_p_red_bc_efet_opc,
                modelo.a043_v_bc_efet_opc,
                modelo.a043_p_icms_efet_opc,
                modelo.a043_v_icms_efet_opc,
                modelo.a043_v_bc_st_dest_opc,
                modelo.a043_v_icms_st_dest_opc,
                modelo.a043_v_bc_uf_dest,
                modelo.a043_v_bc_fcp_uf_dest_opc,
                modelo.a043_p_fcp_uf_dest_opc,
                modelo.a043_p_icms_uf_dest,
                modelo.a043_p_icms_inter,
                modelo.a043_p_icms_inter_part,
                modelo.a043_v_fcp_uf_dest_opc,
                modelo.a043_v_icms_uf_dest,
                modelo.a043_v_icms_uf_remet,
                modelo.a043_usa_cfop,
                modelo.a043_ibs,
                modelo.a043_ibs_aliquota,
                modelo.a043_ibs_base_calc,
                modelo.a043_iss,
                modelo.a043_iss_aliquota,
                modelo.a043_iss_base_calc,
                modelo.a043_cbs,
                modelo.a043_cbs_aliquota,
                modelo.a043_cbs_base_calc,
                modelo.a043_cod_iva,
                modelo.a043_cod_cidade,
                modelo.a043_cst_ibs,
                modelo.a043_cst_iss,
                modelo.a043_cst_cbs,)
            cursor.execute(sql, params)
            self.conexao.commit()
            self.logger.info(f"Registro inserido com sucesso em {self.tabela}.")
            return modelo
        except Exception as e:
            self.conexao.rollback()
            self.logger.error(f"Erro ao inserir em {self.tabela}: {e}")
            raise Exception(f"Erro ao inserir em {self.tabela}: {e}")

    def update(self, modelo: 'a043_tes') -> 'a043_tes':
        try:
            cursor = self.conexao.cursor()
            sql = f"""UPDATE {self.tabela} SET a043_sequencial = ?, a043_descricao = ?, a043_codigo_fiscal = ?, a043_tipo_tes = ?, a043_atualiza_est = ?, a043_gera_financeiro = ?, a043_estado = ?, a043_obs = ?, a043_mov_cta_capital = ?, a043_mov_cta_socio = ?, a043_mov_desp_secagem = ?, a043_especie_pessoa = ?, a043_cat_pessoa = ?, a043_tributacao = ?, a043_base_calc_icm = ?, a043_icm = ?, a043_cod_sit_trib = ?, a043_mensagem_nf = ?, a043_utiliza_preco_pauta = ?, a043_funrural = ?, a043_pis = ?, a043_cofins = ?, a043_ipi = ?, a043_desc_cfop = ?, a043_cod_pessoa = ?, a043_operacao_tes = ?, a043_mov_custo = ?, a043_cod_tes_estorno = ?, a043_cod_col_mapa = ?, a043_finalidade_nfe = ?, a043_mod_base_calculo = ?, a043_mod_base_calculo_substituicao = ?, a043_situacao_tributaria_cofins = ?, a043_situacao_tributaria_pis = ?, a043_base_calculo_cofins = ?, a043_base_calculo_frete = ?, a043_aliquota_frete = ?, a043_obs_fiscal = ?, a043_obs_contribuinte = ?, a043_base_calculo_pis = ?, a043_margem_subst_tributaria = ?, a043_perc_red_base_cal_substituicao = ?, a043_preco_produto = ?, a043_permite_nf = ?, a043_issqn = ?, a043_bc_ipi = ?, a043_mot_desoneracao = ?, a043_exige_nf_prod = ?, a043_vinculo_doc_fiscal = ?, a043_funrural_ent_sai = ?, a043_escrita = ?, a043_ajuste_credito = ?, a043_mensagem_nf_01 = ?, a043_tab_pis = ?, a043_per_pis_socio = ?, a043_base_pis_socio = ?, a043_tab_cofins = ?, a043_per_cofins_socio = ?, a043_base_cofins_socio = ?, a043_cod_Enq_ipi = ?, a043_cst_ipi = ?, a043_usa_trib_pis = ?, a043_p_senar = ?, a043_bc_senar = ?, a043_usa_produtos = ?, a043_cod_aj_apuracao_deducao = ?, a043_cod_ocorrencia_aj_icms = ?, a043_cod_reflexo_apur_icms = ?, a043_cod_tipo_apuracao = ?, a043_cod_responsabilidade = ?, a043_cod_influencia_recolhimento = ?, a043_cod_origem_tributacao = ?, a043_cod_aj_icms_ex_icms = ?, a043_cod_obrigacao_a_recolher = ?, a043_cod_tipo_utilizacao_credito = ?, a043_ajuste_debito = ?, a043_cod_tipo_credito = ?, a043_usa_senar = ?, a043_usuario = ?, a043_datetime = ?, a043_pCredSN = ?, a043_gera_sped = ?, a043_permite_ibpt = ?, a043_depreciacao_anual = ?, a043_percentual_residual = ?, a043_usa_funrural = ?, a043_pDif = ?, a043_pMVAST = ?, a043_pEntMVAST = ?, a043_AliqIntST = ?, a043_AliqST = ?, a043_envia_deposito = ?, a043_tipo_preco = ?, a043_pBCFCP = ?, a043_pFCP = ?, a043_pBCFCPST = ?, a043_pFCPST = ?, a043_pBCFCPRet = ?, a043_pFCPRet = ?, a043_pST = ?, a043_usa_FCP = ?, a043_usa_trib_serv = ?, a043_red_bc_csll = ?, a043_perc_csll = ?, a043_red_bc_irrf = ?, a043_perc_irrf = ?, a043_red_bc_inss = ?, a043_perc_inss = ?, a043_bc_ret = ?, a043_aliq_ret = ?, a043_bc_ret_sub = ?, a043_aliq_ret_sub = ?, a043_perc_nret_princ = ?, a043_perc_ret_15 = ?, a043_perc_ret_20 = ?, a043_perc_ret_25 = ?, a043_perc_nret_adic = ?, a043_v_bc_st_ret_opc = ?, a043_p_st_opc = ?, a043_v_icms_substituto_opc = ?, a043_v_icms_st_ret_opc = ?, a043_v_bc_fcp_st_ret_opc = ?, a043_p_fcp_st_ret_opc = ?, a043_v_fcp_st_ret_opc = ?, a043_p_red_bc_efet_opc = ?, a043_v_bc_efet_opc = ?, a043_p_icms_efet_opc = ?, a043_v_icms_efet_opc = ?, a043_v_bc_st_dest_opc = ?, a043_v_icms_st_dest_opc = ?, a043_v_bc_uf_dest = ?, a043_v_bc_fcp_uf_dest_opc = ?, a043_p_fcp_uf_dest_opc = ?, a043_p_icms_uf_dest = ?, a043_p_icms_inter = ?, a043_p_icms_inter_part = ?, a043_v_fcp_uf_dest_opc = ?, a043_v_icms_uf_dest = ?, a043_v_icms_uf_remet = ?, a043_usa_cfop = ?, a043_ibs = ?, a043_ibs_aliquota = ?, a043_ibs_base_calc = ?, a043_iss = ?, a043_iss_aliquota = ?, a043_iss_base_calc = ?, a043_cbs = ?, a043_cbs_aliquota = ?, a043_cbs_base_calc = ?, a043_cod_iva = ?, a043_cod_cidade = ?, a043_cst_ibs = ?, a043_cst_iss = ?, a043_cst_cbs = ?
                      WHERE {self.chave_primaria} = ?"""
            params = (modelo.a043_sequencial,
                modelo.a043_descricao,
                modelo.a043_codigo_fiscal,
                modelo.a043_tipo_tes,
                modelo.a043_atualiza_est,
                modelo.a043_gera_financeiro,
                modelo.a043_estado,
                modelo.a043_obs,
                modelo.a043_mov_cta_capital,
                modelo.a043_mov_cta_socio,
                modelo.a043_mov_desp_secagem,
                modelo.a043_especie_pessoa,
                modelo.a043_cat_pessoa,
                modelo.a043_tributacao,
                modelo.a043_base_calc_icm,
                modelo.a043_icm,
                modelo.a043_cod_sit_trib,
                modelo.a043_mensagem_nf,
                modelo.a043_utiliza_preco_pauta,
                modelo.a043_funrural,
                modelo.a043_pis,
                modelo.a043_cofins,
                modelo.a043_ipi,
                modelo.a043_desc_cfop,
                modelo.a043_cod_pessoa,
                modelo.a043_operacao_tes,
                modelo.a043_mov_custo,
                modelo.a043_cod_tes_estorno,
                modelo.a043_cod_col_mapa,
                modelo.a043_finalidade_nfe,
                modelo.a043_mod_base_calculo,
                modelo.a043_mod_base_calculo_substituicao,
                modelo.a043_situacao_tributaria_cofins,
                modelo.a043_situacao_tributaria_pis,
                modelo.a043_base_calculo_cofins,
                modelo.a043_base_calculo_frete,
                modelo.a043_aliquota_frete,
                modelo.a043_obs_fiscal,
                modelo.a043_obs_contribuinte,
                modelo.a043_base_calculo_pis,
                modelo.a043_margem_subst_tributaria,
                modelo.a043_perc_red_base_cal_substituicao,
                modelo.a043_preco_produto,
                modelo.a043_permite_nf,
                modelo.a043_issqn,
                modelo.a043_bc_ipi,
                modelo.a043_mot_desoneracao,
                modelo.a043_exige_nf_prod,
                modelo.a043_vinculo_doc_fiscal,
                modelo.a043_funrural_ent_sai,
                modelo.a043_escrita,
                modelo.a043_ajuste_credito,
                modelo.a043_mensagem_nf_01,
                modelo.a043_tab_pis,
                modelo.a043_per_pis_socio,
                modelo.a043_base_pis_socio,
                modelo.a043_tab_cofins,
                modelo.a043_per_cofins_socio,
                modelo.a043_base_cofins_socio,
                modelo.a043_cod_Enq_ipi,
                modelo.a043_cst_ipi,
                modelo.a043_usa_trib_pis,
                modelo.a043_p_senar,
                modelo.a043_bc_senar,
                modelo.a043_usa_produtos,
                modelo.a043_cod_aj_apuracao_deducao,
                modelo.a043_cod_ocorrencia_aj_icms,
                modelo.a043_cod_reflexo_apur_icms,
                modelo.a043_cod_tipo_apuracao,
                modelo.a043_cod_responsabilidade,
                modelo.a043_cod_influencia_recolhimento,
                modelo.a043_cod_origem_tributacao,
                modelo.a043_cod_aj_icms_ex_icms,
                modelo.a043_cod_obrigacao_a_recolher,
                modelo.a043_cod_tipo_utilizacao_credito,
                modelo.a043_ajuste_debito,
                modelo.a043_cod_tipo_credito,
                modelo.a043_usa_senar,
                modelo.a043_usuario,
                modelo.a043_datetime,
                modelo.a043_pCredSN,
                modelo.a043_gera_sped,
                modelo.a043_permite_ibpt,
                modelo.a043_depreciacao_anual,
                modelo.a043_percentual_residual,
                modelo.a043_usa_funrural,
                modelo.a043_pDif,
                modelo.a043_pMVAST,
                modelo.a043_pEntMVAST,
                modelo.a043_AliqIntST,
                modelo.a043_AliqST,
                modelo.a043_envia_deposito,
                modelo.a043_tipo_preco,
                modelo.a043_pBCFCP,
                modelo.a043_pFCP,
                modelo.a043_pBCFCPST,
                modelo.a043_pFCPST,
                modelo.a043_pBCFCPRet,
                modelo.a043_pFCPRet,
                modelo.a043_pST,
                modelo.a043_usa_FCP,
                modelo.a043_usa_trib_serv,
                modelo.a043_red_bc_csll,
                modelo.a043_perc_csll,
                modelo.a043_red_bc_irrf,
                modelo.a043_perc_irrf,
                modelo.a043_red_bc_inss,
                modelo.a043_perc_inss,
                modelo.a043_bc_ret,
                modelo.a043_aliq_ret,
                modelo.a043_bc_ret_sub,
                modelo.a043_aliq_ret_sub,
                modelo.a043_perc_nret_princ,
                modelo.a043_perc_ret_15,
                modelo.a043_perc_ret_20,
                modelo.a043_perc_ret_25,
                modelo.a043_perc_nret_adic,
                modelo.a043_v_bc_st_ret_opc,
                modelo.a043_p_st_opc,
                modelo.a043_v_icms_substituto_opc,
                modelo.a043_v_icms_st_ret_opc,
                modelo.a043_v_bc_fcp_st_ret_opc,
                modelo.a043_p_fcp_st_ret_opc,
                modelo.a043_v_fcp_st_ret_opc,
                modelo.a043_p_red_bc_efet_opc,
                modelo.a043_v_bc_efet_opc,
                modelo.a043_p_icms_efet_opc,
                modelo.a043_v_icms_efet_opc,
                modelo.a043_v_bc_st_dest_opc,
                modelo.a043_v_icms_st_dest_opc,
                modelo.a043_v_bc_uf_dest,
                modelo.a043_v_bc_fcp_uf_dest_opc,
                modelo.a043_p_fcp_uf_dest_opc,
                modelo.a043_p_icms_uf_dest,
                modelo.a043_p_icms_inter,
                modelo.a043_p_icms_inter_part,
                modelo.a043_v_fcp_uf_dest_opc,
                modelo.a043_v_icms_uf_dest,
                modelo.a043_v_icms_uf_remet,
                modelo.a043_usa_cfop,
                modelo.a043_ibs,
                modelo.a043_ibs_aliquota,
                modelo.a043_ibs_base_calc,
                modelo.a043_iss,
                modelo.a043_iss_aliquota,
                modelo.a043_iss_base_calc,
                modelo.a043_cbs,
                modelo.a043_cbs_aliquota,
                modelo.a043_cbs_base_calc,
                modelo.a043_cod_iva,
                modelo.a043_cod_cidade,
                modelo.a043_cst_ibs,
                modelo.a043_cst_iss,
                modelo.a043_cst_cbs,
                modelo.a043_codigo)
            cursor.execute(sql, params)
            self.conexao.commit()
            self.logger.info(f"Registro atualizado com sucesso em {self.tabela}.")
            return modelo
        except Exception as e:
            self.conexao.rollback()
            self.logger.error(f"Erro ao atualizar em {self.tabela}: {e}")
            raise Exception(f"Erro ao atualizar em {self.tabela}: {e}")

    def delete(self, id: str) -> None:
        try:
            cursor = self.conexao.cursor()
            sql = f"DELETE FROM {self.tabela} WHERE {self.chave_primaria} = ?"
            cursor.execute(sql, (id,))
            self.conexao.commit()
            self.logger.info(f"Registro deletado com sucesso de {self.tabela}, ID: {id}")
        except Exception as e:
            self.conexao.rollback()
            self.logger.error(f"Erro ao deletar em {self.tabela}: {e}")
            raise Exception(f"Erro ao deletar em {self.tabela}: {e}")

    def get_by_id(self, id: str) -> Union['a043_tes', None]:
        try:
            cursor = self.conexao.cursor()
            sql = f"SELECT * FROM {self.tabela} WHERE {self.chave_primaria} = ?"
            cursor.execute(sql, (id,))
            row = cursor.fetchone()
            return self._row_to_object(row) if row else None
        except Exception as e:
            self.logger.error(f"Erro ao buscar por ID em {self.tabela}: {e}")
            raise Exception(f"Erro ao buscar por ID em {self.tabela}: {e}")

    def list_all(self) -> List['a043_tes']:
        try:
            cursor = self.conexao.cursor()
            sql = f"SELECT * FROM {self.tabela}"
            cursor.execute(sql)
            rows = cursor.fetchall()
            return [self._row_to_object(row) for row in rows]
        except Exception as e:
            self.logger.error(f"Erro ao listar todos de {self.tabela}: {e}")
            raise Exception(f"Erro ao listar todos de {self.tabela}: {e}")
